package core

import (
	"testing"

	"github.com/samber/lo"
	"github.com/stretchr/testify/assert"
	"github.com/mavryk-network/mavpay/common"
	"github.com/mavryk-network/mavpay/configuration"
	"github.com/mavryk-network/mavpay/state"
	"github.com/mavryk-network/mavpay/test/mock"
	"github.com/mavryk-network/gomavryk/codec"
	"github.com/mavryk-network/gomavryk/rpc"
	"github.com/mavryk-network/gomavryk/mavryk"
)

type mockPrepareCollector struct {
	mock.EmptyCollector
}

func (engine *mockPrepareCollector) GetId() string {
	return "mockPrepareCollector"
}

func (engine *mockPrepareCollector) IsRevealed(address mavryk.Address) (bool, error) {
	return true, nil
}

func (engine *mockPrepareCollector) GetBalance(addr mavryk.Address) (mavryk.Z, error) {
	return mavryk.NewZ(10000000000), nil
}

func (engine *mockPrepareCollector) Simulate(o *codec.Op, publicKey mavryk.Key) (*rpc.Receipt, error) {
	// rawRcpt := `{"Block":"BKiHLREqU3JkXfzEDYAkmmfX48gBDtYhMrpA98s7Aq4SzbUAB6M","Height":0,"List":0,"Pos":0,"Op":{"protocol":"PrihK96nBAFSxVL1GLJTVhu9YnzkMFiBeuJRPA8NwuZVZCE1L6i","chain_id":"NetXH12Aer3be93","hash":"oneDGhZacw99EEFaYDTtWfz5QEhUW3PPVFsHa7GShnLPuDn7gSd","branch":"BKiHLREqU3JkXfzEDYAkmmfX48gBDtYhMrpA98s7Aq4SzbUAB6M","contents":[{"kind":"transaction","metadata":{"balance_updates":null,"operation_result":{"status":"applied","balance_updates":[{"kind":"contract","origin":"block","category":"","change":"-1","contract":"mv1VnvaH7sWiY6jRX57VCFnpPcax3FnQ2zjb","delegate":"","committer":"","participation":false,"revelation":false,"level":0,"cycle":0,"bond_id":{"smart_rollup":""},"staker":{"contract":"","delegate":"","baker":"","baker_own_stake":"","baker_edge":""},"delayed_operation_hash":"oneDGhZacw99EEFaYDTtWfz5QEhUW3PPVFsHa7GShnLPuDn7gSd"},{"kind":"contract","origin":"block","category":"","change":"1","contract":"mv2burnburnburnburnburnburnbur7hzNeg","delegate":"","committer":"","participation":false,"revelation":false,"level":0,"cycle":0,"bond_id":{"smart_rollup":""},"staker":{"contract":"","delegate":"","baker":"","baker_own_stake":"","baker_edge":""},"delayed_operation_hash":"oneDGhZacw99EEFaYDTtWfz5QEhUW3PPVFsHa7GShnLPuDn7gSd"}],"consumed_gas":"0","consumed_milligas":"2170676","allocated_destination_contract":false,"originated_contracts":null,"storage_size":"0","paid_storage_size_diff":"0","global_address":"exprtWsu7N8st7XBhS685Qa2B4xP6TuTN9ve9UPCU29fV94ySDo5Va","ticket_updates":null,"ticket_receipt":null,"originated_rollup":"","level":0,"slot_header":{"version":"","level":0,"index":0,"commitment":""}},"delegate":"","level":0,"forbidden_delegate":""},"source":"mv1VnvaH7sWiY6jRX57VCFnpPcax3FnQ2zjb","fee":"0","counter":"46810704","gas_limit":"520000","storage_limit":"30000","destination":"mv2burnburnburnburnburnburnbur7hzNeg","amount":"1"},{"kind":"transaction","metadata":{"balance_updates":null,"operation_result":{"status":"applied","balance_updates":[{"kind":"contract","origin":"block","category":"","change":"-1","contract":"mv1VnvaH7sWiY6jRX57VCFnpPcax3FnQ2zjb","delegate":"","committer":"","participation":false,"revelation":false,"level":0,"cycle":0,"bond_id":{"smart_rollup":""},"staker":{"contract":"","delegate":"","baker":"","baker_own_stake":"","baker_edge":""},"delayed_operation_hash":"oneDGhZacw99EEFaYDTtWfz5QEhUW3PPVFsHa7GShnLPuDn7gSd"},{"kind":"contract","origin":"block","category":"","change":"1","contract":"mv2burnburnburnburnburnburnbur7hzNeg","delegate":"","committer":"","participation":false,"revelation":false,"level":0,"cycle":0,"bond_id":{"smart_rollup":""},"staker":{"contract":"","delegate":"","baker":"","baker_own_stake":"","baker_edge":""},"delayed_operation_hash":"oneDGhZacw99EEFaYDTtWfz5QEhUW3PPVFsHa7GShnLPuDn7gSd"}],"consumed_gas":"0","consumed_milligas":"2100040","allocated_destination_contract":false,"originated_contracts":null,"storage_size":"0","paid_storage_size_diff":"0","global_address":"exprtWsu7N8st7XBhS685Qa2B4xP6TuTN9ve9UPCU29fV94ySDo5Va","ticket_updates":null,"ticket_receipt":null,"originated_rollup":"","level":0,"slot_header":{"version":"","level":0,"index":0,"commitment":""}},"delegate":"","level":0,"forbidden_delegate":""},"source":"mv1VnvaH7sWiY6jRX57VCFnpPcax3FnQ2zjb","fee":"0","counter":"46810705","gas_limit":"520000","storage_limit":"30000","destination":"mv2burnburnburnburnburnburnbur7hzNeg","amount":"1"}],"signature":"sigMzJ4GVAvXEd2RjsKGfG2H9QvqTSKCZsuB2KiHbZRGFz72XgF6KaKADznh674fQgBatxw3xdHqTtMHUZAGRprxy64wg1aq"}}`

	var rcpt rpc.Receipt
	rcpt.Block = mavryk.MustParseBlockHash("BKiHLREqU3JkXfzEDYAkmmfX48gBDtYhMrpA98s7Aq4SzbUAB6M")
	rcpt.Height = 0
	rcpt.List = 0
	rcpt.Pos = 0
	rcpt.Op = &rpc.Operation{
		Protocol: mavryk.MustParseProtocolHash("PtSeouLouXkxhg39oWzjxDWaCydNfR3RxCUrNe4Q9Ro8BTehcbh"),
		ChainID:  mavryk.MustParseChainIdHash("NetXH12Aer3be93"),
		Hash:     mavryk.MustParseOpHash("oneDGhZacw99EEFaYDTtWfz5QEhUW3PPVFsHa7GShnLPuDn7gSd"),
		Branch:   mavryk.MustParseBlockHash("BKiHLREqU3JkXfzEDYAkmmfX48gBDtYhMrpA98s7Aq4SzbUAB6M"),
		Contents: lo.Map(o.Contents, func(c codec.Operation, _ int) rpc.TypedOperation {
			tx, isTransaction := c.(*codec.Transaction)
			if !isTransaction {
				panic("only transaction is supported in mock")
			}
			tx.GasLimit = 520000
			tx.StorageLimit = 30000
			tx.Fee = 1000
			return rpc.Transaction{
				Manager: rpc.Manager{
					GasLimit:     520000,
					StorageLimit: 30000,
					Fee:          1000,
				},
				Destination: tx.Destination,
				Amount:      tx.Amount.Int64(),
			}
		}),
	}

	return &rcpt, nil
}

type mockPrepareReporter struct {
	mock.EmptyReporter
}

func (engine *mockPrepareReporter) GetExistingReports(cycle int64) ([]common.PayoutReport, error) {
	switch cycle {
	case 55:
		return []common.PayoutReport{
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1Vv3mBK3Q166DndgzfaMux48Ye5Hmq9oGK"),
				Cycle:            55,
				Recipient:        mavryk.MustParseAddress("mv1Vv3mBK3Q166DndgzfaMux48Ye5Hmq9oGK"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(170719784),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(10963),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(1354),
				IsSuccess:        true,
			},
		}, nil
	case 1017:
		return []common.PayoutReport{
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1U7MzxbVWSVnjYWMwvrkWxReQwSzPkXcvB"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("mv1U7MzxbVWSVnjYWMwvrkWxReQwSzPkXcvB"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(12750656),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(818),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(101),
				IsSuccess:        true,
			},
		}, nil
	}
	return []common.PayoutReport{}, nil
}

// TODO:
func Test_Prepare(t *testing.T) {
	assert := assert.New(t)

	var blueprint1 common.CyclePayoutBlueprint = common.CyclePayoutBlueprint{
		Cycle:                    55,
		OwnStakedBalance:         mavryk.NewZ(16421212933),
		OwnDelegatedBalance:      mavryk.NewZ(275708698),
		ExternalStakedBalance:    mavryk.NewZ(29383795329),
		ExternalDelegatedBalance: mavryk.NewZ(49100747788),
		EarnedBlockFees:          mavryk.NewZ(17100),
		EarnedRewards:            mavryk.NewZ(3545308),
		EarnedTotal:              mavryk.NewZ(3562408),
		BondIncome:               mavryk.NewZ(19693),
		FeeIncome:                mavryk.NewZ(385753),
		IncomeTotal:              mavryk.NewZ(405446),
		DonatedBonds:             mavryk.NewZ(198),
		DonatedFees:              mavryk.NewZ(3896),
		DonatedTotal:             mavryk.NewZ(4094),
		Payouts: []common.PayoutRecipe{
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1XHWTsUduZo49c36XvUeBggTVG4FCGz12p"),
				Cycle:            55,
				Recipient:        mavryk.MustParseAddress("mv1XHWTsUduZo49c36XvUeBggTVG4FCGz12p"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(18996459719),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(1219794),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(150761),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1X9TXhN3ywRxytgkDvGq6Bcaf7smz4chYU"),
				Cycle:            55,
				Recipient:        mavryk.MustParseAddress("mv1X9TXhN3ywRxytgkDvGq6Bcaf7smz4chYU"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(16995702660),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(1091322),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(134882),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1X2SWH5ewCXYzTE8G37tw9pHAz8LUuceJj"),
				Cycle:            55,
				Recipient:        mavryk.MustParseAddress("mv1X2SWH5ewCXYzTE8G37tw9pHAz8LUuceJj"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(6704943203),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(430535),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(53212),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1WfXzCwhHES8YcDaJDArzxhCLQLQFxYQGU"),
				Cycle:            55,
				Recipient:        mavryk.MustParseAddress("mv1WfXzCwhHES8YcDaJDArzxhCLQLQFxYQGU"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(2067404437),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(132751),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(16407),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1NRwexo4LRtPixUXhUQLbQyDnWnQ682GTd"),
				Cycle:            55,
				Recipient:        mavryk.MustParseAddress("mv1NRwexo4LRtPixUXhUQLbQyDnWnQ682GTd"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(767347858),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(49273),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(6089),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1Wc4TxW2pNrZe4fvUh6Ux9Z6bdSdCJgtte"),
				Cycle:            55,
				Recipient:        mavryk.MustParseAddress("mv1Wc4TxW2pNrZe4fvUh6Ux9Z6bdSdCJgtte"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(664759189),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(42685),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(5275),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1WV8nm6rnkpk6inA8Eqe74Gr36xkmhy9aC"),
				Cycle:            55,
				Recipient:        mavryk.MustParseAddress("mv1WV8nm6rnkpk6inA8Eqe74Gr36xkmhy9aC"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(598755901),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(38447),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(4751),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1WLJr1tSbZ1AcxNLN9BaocXw654EtaXUGX"),
				Cycle:            55,
				Recipient:        mavryk.MustParseAddress("mv1WLJr1tSbZ1AcxNLN9BaocXw654EtaXUGX"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(507845869),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(32610),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(4030),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1WG5a7s8o8KU5x1vVGgWHWEBQvLveB766Q"),
				Cycle:            55,
				Recipient:        mavryk.MustParseAddress("mv1WG5a7s8o8KU5x1vVGgWHWEBQvLveB766Q"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(405103709),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(26013),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(3214),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1WCTuyzCrBZMtHEJKXcxR9RWNCEBfoyM3Z"),
				Cycle:            55,
				Recipient:        mavryk.MustParseAddress("mv1WCTuyzCrBZMtHEJKXcxR9RWNCEBfoyM3Z"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(313906924),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(20156),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(2491),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1Vv3mBK3Q166DndgzfaMux48Ye5Hmq9oGK"),
				Cycle:            55,
				Recipient:        mavryk.MustParseAddress("mv1Vv3mBK3Q166DndgzfaMux48Ye5Hmq9oGK"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(170719784),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(10963),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(1354),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1VnvaH7sWiY6jRX57VCFnpPcax3FnQ2zjb"),
				Cycle:            55,
				Recipient:        mavryk.MustParseAddress("mv1VnvaH7sWiY6jRX57VCFnpPcax3FnQ2zjb"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(165652388),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(10637),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(1314),
				Note:             "RECIPIENT_TARGETS_PAYOUT",
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1VWJUsAUkWhXN4EqdeRQEHF1jobTN4KjMc"),
				Cycle:            55,
				Recipient:        mavryk.MustParseAddress("mv1VWJUsAUkWhXN4EqdeRQEHF1jobTN4KjMc"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(161298995),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(10357),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(1280),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1VJqqe9A4otkv32xZZuj663PszaBxXAvV3"),
				Cycle:            55,
				Recipient:        mavryk.MustParseAddress("mv1VJqqe9A4otkv32xZZuj663PszaBxXAvV3"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(94164895),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(6046),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(747),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1V7DmkL7ApfzW9x4Z888K9SBwMvhY12S3G"),
				Cycle:            55,
				Recipient:        mavryk.MustParseAddress("mv1V7DmkL7ApfzW9x4Z888K9SBwMvhY12S3G"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(75318303),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(4837),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(597),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1V4ntsKBfPWueYCSVjBLA8WsRwr89otXqC"),
				Cycle:            55,
				Recipient:        mavryk.MustParseAddress("mv1V4ntsKBfPWueYCSVjBLA8WsRwr89otXqC"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(74317010),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(4772),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(589),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1V1jSM6s66pPjoSFh2ysafeJubmQuH6EPy"),
				Cycle:            55,
				Recipient:        mavryk.MustParseAddress("mv1V1jSM6s66pPjoSFh2ysafeJubmQuH6EPy"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(70644509),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(4536),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(560),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1UwtfjoqsW2VSnh6ua9bXWqQXC75Hc1sRT"),
				Cycle:            55,
				Recipient:        mavryk.MustParseAddress("mv1UwtfjoqsW2VSnh6ua9bXWqQXC75Hc1sRT"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(50000001),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(3211),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(396),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1UqEZgmL7M5X836tX5eU3ToTrrBeSwpsQ5"),
				Cycle:            55,
				Recipient:        mavryk.MustParseAddress("mv1UqEZgmL7M5X836tX5eU3ToTrrBeSwpsQ5"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(34441415),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(2211),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(273),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1UaZuPQcBSZ6vBk8dqL8uLpMJvc4rFEwJt"),
				Cycle:            55,
				Recipient:        mavryk.MustParseAddress("mv1UaZuPQcBSZ6vBk8dqL8uLpMJvc4rFEwJt"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(32415471),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(2081),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(257),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1UZF5SdgTcosigsnovTEbgUaFEiNCsG9NJ"),
				Cycle:            55,
				Recipient:        mavryk.MustParseAddress("mv1UZF5SdgTcosigsnovTEbgUaFEiNCsG9NJ"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(20256873),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(1301),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(160),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1UYABMCi3JHWKhsjA5uqjQkX6VpbbMRg6V"),
				Cycle:            55,
				Recipient:        mavryk.MustParseAddress("mv1UYABMCi3JHWKhsjA5uqjQkX6VpbbMRg6V"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(18888009),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(1213),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(149),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1UVKnfHCrzbUcfHS63xFeYbD4PfBCNAfYw"),
				Cycle:            55,
				Recipient:        mavryk.MustParseAddress("mv1UVKnfHCrzbUcfHS63xFeYbD4PfBCNAfYw"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(17427981),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(1119),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(138),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1UPcgbYJCHWj6xg15VD2z1mAPMHH1VY3Sn"),
				Cycle:            55,
				Recipient:        mavryk.MustParseAddress("mv1UPcgbYJCHWj6xg15VD2z1mAPMHH1VY3Sn"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(14207578),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(913),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(112),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1U7MzxbVWSVnjYWMwvrkWxReQwSzPkXcvB"),
				Cycle:            55,
				Recipient:        mavryk.MustParseAddress("mv1U7MzxbVWSVnjYWMwvrkWxReQwSzPkXcvB"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(12750656),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(818),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(101),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1TnGFAE2ehvQe5F2U5HbWZWb2FX423Vd8i"),
				Cycle:            55,
				Recipient:        mavryk.MustParseAddress("mv1TnGFAE2ehvQe5F2U5HbWZWb2FX423Vd8i"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(11966885),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(769),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(94),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1Tf75a2fUGmrThNuyse4vKFbPWM697SrNY"),
				Cycle:            55,
				Recipient:        mavryk.MustParseAddress("mv1Tf75a2fUGmrThNuyse4vKFbPWM697SrNY"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(11307149),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(726),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(89),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1Te9TpceACAx9ovhntt2VdsvkpLEDqvBvn"),
				Cycle:            55,
				Recipient:        mavryk.MustParseAddress("mv1Te9TpceACAx9ovhntt2VdsvkpLEDqvBvn"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(10889299),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(699),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(86),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1TWUZkUjutJHgo9t7FqxTNiqoFPuGEC4Bq"),
				Cycle:            55,
				Recipient:        mavryk.MustParseAddress("mv1TWUZkUjutJHgo9t7FqxTNiqoFPuGEC4Bq"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(7355283),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(472),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(58),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1TUaXztR5AK1BiRBxkFVLL49rkYLY3UqvZ"),
				Cycle:            55,
				Recipient:        mavryk.MustParseAddress("mv1TUaXztR5AK1BiRBxkFVLL49rkYLY3UqvZ"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(5221495),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(335),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(41),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1TSNZFAJaf8EQw4wreZjXtrcqZ8h4DFguU"),
				Cycle:            55,
				Recipient:        mavryk.MustParseAddress("mv1TSNZFAJaf8EQw4wreZjXtrcqZ8h4DFguU"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(2939210),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(189),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(23),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1TNgdUnE5udE6azQKy4HmDQJUWnKq2XQHu"),
				Cycle:            55,
				Recipient:        mavryk.MustParseAddress("mv1TNgdUnE5udE6azQKy4HmDQJUWnKq2XQHu"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(1984760),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(128),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(15),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1TGgFyRj2X6HovN3bCVSzMNZpJAuZGfmah"),
				Cycle:            55,
				Recipient:        mavryk.MustParseAddress("mv1TGgFyRj2X6HovN3bCVSzMNZpJAuZGfmah"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(1866216),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(120),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(14),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1SqGXUmNrBnnxE8zGueLteyK8nGf8MEX3A"),
				Cycle:            55,
				Recipient:        mavryk.MustParseAddress("mv1SqGXUmNrBnnxE8zGueLteyK8nGf8MEX3A"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(1641573),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(106),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(12),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1SpdbvjSeBH2sVGbwWdS6PjT3fTjcJXrND"),
				Cycle:            55,
				Recipient:        mavryk.MustParseAddress("mv1SpdbvjSeBH2sVGbwWdS6PjT3fTjcJXrND"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(1502458),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(97),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(11),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1SoxkkpjGAxigEX9jYEZjnhytAwYiJQXSM"),
				Cycle:            55,
				Recipient:        mavryk.MustParseAddress("mv1SoxkkpjGAxigEX9jYEZjnhytAwYiJQXSM"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(1459627),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(94),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(11),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1SXRSyhLnM9gSCc4YK3Ve6usdUN3pxNUtP"),
				Cycle:            55,
				Recipient:        mavryk.MustParseAddress("mv1SXRSyhLnM9gSCc4YK3Ve6usdUN3pxNUtP"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(1425001),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(91),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(11),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1SEq4K9xCso46WdqhDTPLHU6intuatA5Rz"),
				Cycle:            55,
				Recipient:        mavryk.MustParseAddress("mv1SEq4K9xCso46WdqhDTPLHU6intuatA5Rz"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(1406177),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(90),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(11),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1S8DRaNqHFRMNkpPgz3m5VnDGNSp4g4E71"),
				Cycle:            55,
				Recipient:        mavryk.MustParseAddress("mv1S8DRaNqHFRMNkpPgz3m5VnDGNSp4g4E71"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(1322354),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(85),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(10),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1RJjoUbdiZhG5ifQteRXVMPbooozCXwSbQ"),
				Cycle:            55,
				Recipient:        mavryk.MustParseAddress("mv1RJjoUbdiZhG5ifQteRXVMPbooozCXwSbQ"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(990125),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(64),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(7),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1REFFS2cy5hwqiDtxgeQmMpWTgoJdTwnBQ"),
				Cycle:            55,
				Recipient:        mavryk.MustParseAddress("mv1REFFS2cy5hwqiDtxgeQmMpWTgoJdTwnBQ"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(960009),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(62),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(7),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1QuSnBhYgaYwSq9Xy2985c5paAsFp9wBC5"),
				Cycle:            55,
				Recipient:        mavryk.MustParseAddress("mv1QuSnBhYgaYwSq9Xy2985c5paAsFp9wBC5"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(370571),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(24),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(2),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("KT1AmQTRDjTwfJDASJRJZdd7uJwDqs5W2mjA"),
				Cycle:            55,
				Recipient:        mavryk.MustParseAddress("KT1AmQTRDjTwfJDASJRJZdd7uJwDqs5W2mjA"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(289285),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(18),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(2),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1QtzoiuEztATbwANYP4gtEAdczn5ddV4Nj"),
				Cycle:            55,
				Recipient:        mavryk.MustParseAddress("mv1QtzoiuEztATbwANYP4gtEAdczn5ddV4Nj"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(275000),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(17),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(2),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1QmgAgBAMDHrx5th182efP3oygKWr1C2uU"),
				Cycle:            55,
				Recipient:        mavryk.MustParseAddress("mv1QmgAgBAMDHrx5th182efP3oygKWr1C2uU"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(200001),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(13),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(1),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1Qa4KUBhQKbwypURu3DCZVd1eyfAGwiVWp"),
				Cycle:            55,
				Recipient:        mavryk.MustParseAddress("mv1Qa4KUBhQKbwypURu3DCZVd1eyfAGwiVWp"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(172996),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(11),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(1),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("KT1Kmai449TQT76GZXbihwNFHTUy432y1Z6Y"),
				Cycle:            55,
				Recipient:        mavryk.MustParseAddress("KT1Kmai449TQT76GZXbihwNFHTUy432y1Z6Y"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(164629),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(10),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(1),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1QVVWyMc5yUJSja4ekcSceiw2kr8QnMZbF"),
				Cycle:            55,
				Recipient:        mavryk.MustParseAddress("mv1QVVWyMc5yUJSja4ekcSceiw2kr8QnMZbF"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(162848),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(10),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(1),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1QFwxFkC9c7fezjNE4VPATXfefbam1GFAt"),
				Cycle:            55,
				Recipient:        mavryk.MustParseAddress("mv1QFwxFkC9c7fezjNE4VPATXfefbam1GFAt"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(63473),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(4),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(0),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1Pf1ZpN3v4fBW3oSYhTj4wnf9XTEQATfDK"),
				Cycle:            55,
				Recipient:        mavryk.MustParseAddress("mv1Pf1ZpN3v4fBW3oSYhTj4wnf9XTEQATfDK"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(40787),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(2),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(0),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1PXgWu6bukpMfSCMgmLHqPvwCxUFkVuT3A"),
				Cycle:            55,
				Recipient:        mavryk.MustParseAddress("mv1PXgWu6bukpMfSCMgmLHqPvwCxUFkVuT3A"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(27475),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(1),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(0),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1PM6eS9LcrNZGQGiAuistbK64odUvw5CqG"),
				Cycle:            55,
				Recipient:        mavryk.MustParseAddress("mv1PM6eS9LcrNZGQGiAuistbK64odUvw5CqG"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(8937),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(0),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(0),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("KT19XE62UbrJ2gWW4ZWq2UxTQLhrnjBHLvBm"),
				Cycle:            55,
				Recipient:        mavryk.MustParseAddress("KT19XE62UbrJ2gWW4ZWq2UxTQLhrnjBHLvBm"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(826),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(0),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(0),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1PJLDRgEZGwxwCJsjM4hv3Rhx5AMbYuaJa"),
				Cycle:            55,
				Recipient:        mavryk.MustParseAddress("mv1PJLDRgEZGwxwCJsjM4hv3Rhx5AMbYuaJa"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(1),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(0),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(0),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1PHN4Ck48rVjhj35FGWq23vYVSDKRD5sny"),
				Cycle:            55,
				Recipient:        mavryk.MustParseAddress("mv1PHN4Ck48rVjhj35FGWq23vYVSDKRD5sny"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(1),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(0),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(0),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("KT1FtGbyLR1KV9oQGEYgBUpKPkEC8BcQn4cD"),
				Cycle:            55,
				Recipient:        mavryk.MustParseAddress("KT1FtGbyLR1KV9oQGEYgBUpKPkEC8BcQn4cD"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(0),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(0),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(0),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("KT1B5KPckWy2Mw99ii3wKuE4TQWKKQtSNXFE"),
				Cycle:            55,
				Recipient:        mavryk.MustParseAddress("KT1B5KPckWy2Mw99ii3wKuE4TQWKKQtSNXFE"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(0),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(0),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(0),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.Address{}, // Represents an empty delegator address
				Cycle:            55,
				Recipient:        mavryk.MustParseAddress("mv1WLJr1tSbZ1AcxNLN9BaocXw654EtaXUGX"),
				Kind:             "donation",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(0),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(4094),
				Fee:              mavryk.NewZ(0),
				IsValid:          true,
			},
		},
	}

	var blueprint2 common.CyclePayoutBlueprint = common.CyclePayoutBlueprint{
		Cycle:                    1017,
		OwnStakedBalance:         mavryk.NewZ(16421212933),
		OwnDelegatedBalance:      mavryk.NewZ(275708698),
		ExternalStakedBalance:    mavryk.NewZ(29383795329),
		ExternalDelegatedBalance: mavryk.NewZ(49100747788),
		EarnedBlockFees:          mavryk.NewZ(17100),
		EarnedRewards:            mavryk.NewZ(3545308),
		EarnedTotal:              mavryk.NewZ(3562408),
		BondIncome:               mavryk.NewZ(19693),
		FeeIncome:                mavryk.NewZ(385753),
		IncomeTotal:              mavryk.NewZ(405446),
		DonatedBonds:             mavryk.NewZ(198),
		DonatedFees:              mavryk.NewZ(3896),
		DonatedTotal:             mavryk.NewZ(4094),
		Payouts: []common.PayoutRecipe{
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1XHWTsUduZo49c36XvUeBggTVG4FCGz12p"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("mv1XHWTsUduZo49c36XvUeBggTVG4FCGz12p"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(18996459719),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(1219794),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(150761),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1X9TXhN3ywRxytgkDvGq6Bcaf7smz4chYU"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("mv1X9TXhN3ywRxytgkDvGq6Bcaf7smz4chYU"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(16995702660),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(1091322),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(134882),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1X2SWH5ewCXYzTE8G37tw9pHAz8LUuceJj"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("mv1X2SWH5ewCXYzTE8G37tw9pHAz8LUuceJj"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(6704943203),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(430535),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(53212),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1WfXzCwhHES8YcDaJDArzxhCLQLQFxYQGU"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("mv1WfXzCwhHES8YcDaJDArzxhCLQLQFxYQGU"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(2067404437),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(132751),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(16407),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1NRwexo4LRtPixUXhUQLbQyDnWnQ682GTd"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("mv1NRwexo4LRtPixUXhUQLbQyDnWnQ682GTd"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(767347858),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(49273),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(6089),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1Wc4TxW2pNrZe4fvUh6Ux9Z6bdSdCJgtte"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("mv1Wc4TxW2pNrZe4fvUh6Ux9Z6bdSdCJgtte"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(664759189),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(42685),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(5275),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1WV8nm6rnkpk6inA8Eqe74Gr36xkmhy9aC"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("mv1WV8nm6rnkpk6inA8Eqe74Gr36xkmhy9aC"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(598755901),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(38447),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(4751),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1WLJr1tSbZ1AcxNLN9BaocXw654EtaXUGX"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("mv1WLJr1tSbZ1AcxNLN9BaocXw654EtaXUGX"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(507845869),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(32610),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(4030),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1WG5a7s8o8KU5x1vVGgWHWEBQvLveB766Q"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("mv1WG5a7s8o8KU5x1vVGgWHWEBQvLveB766Q"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(405103709),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(26013),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(3214),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1WCTuyzCrBZMtHEJKXcxR9RWNCEBfoyM3Z"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("mv1WCTuyzCrBZMtHEJKXcxR9RWNCEBfoyM3Z"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(313906924),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(20156),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(2491),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1Vv3mBK3Q166DndgzfaMux48Ye5Hmq9oGK"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("mv1Vv3mBK3Q166DndgzfaMux48Ye5Hmq9oGK"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(170719784),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(10963),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(1354),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1VnvaH7sWiY6jRX57VCFnpPcax3FnQ2zjb"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("mv1VnvaH7sWiY6jRX57VCFnpPcax3FnQ2zjb"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(165652388),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(10637),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(1314),
				Note:             "RECIPIENT_TARGETS_PAYOUT",
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1VWJUsAUkWhXN4EqdeRQEHF1jobTN4KjMc"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("mv1VWJUsAUkWhXN4EqdeRQEHF1jobTN4KjMc"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(161298995),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(10357),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(1280),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1VJqqe9A4otkv32xZZuj663PszaBxXAvV3"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("mv1VJqqe9A4otkv32xZZuj663PszaBxXAvV3"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(94164895),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(6046),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(747),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1V7DmkL7ApfzW9x4Z888K9SBwMvhY12S3G"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("mv1V7DmkL7ApfzW9x4Z888K9SBwMvhY12S3G"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(75318303),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(4837),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(597),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1V4ntsKBfPWueYCSVjBLA8WsRwr89otXqC"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("mv1V4ntsKBfPWueYCSVjBLA8WsRwr89otXqC"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(74317010),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(4772),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(589),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1V1jSM6s66pPjoSFh2ysafeJubmQuH6EPy"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("mv1V1jSM6s66pPjoSFh2ysafeJubmQuH6EPy"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(70644509),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(4536),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(560),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1UwtfjoqsW2VSnh6ua9bXWqQXC75Hc1sRT"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("mv1UwtfjoqsW2VSnh6ua9bXWqQXC75Hc1sRT"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(50000001),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(3211),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(396),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1UqEZgmL7M5X836tX5eU3ToTrrBeSwpsQ5"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("mv1UqEZgmL7M5X836tX5eU3ToTrrBeSwpsQ5"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(34441415),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(2211),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(273),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1UaZuPQcBSZ6vBk8dqL8uLpMJvc4rFEwJt"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("mv1UaZuPQcBSZ6vBk8dqL8uLpMJvc4rFEwJt"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(32415471),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(2081),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(257),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1UZF5SdgTcosigsnovTEbgUaFEiNCsG9NJ"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("mv1UZF5SdgTcosigsnovTEbgUaFEiNCsG9NJ"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(20256873),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(1301),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(160),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1UYABMCi3JHWKhsjA5uqjQkX6VpbbMRg6V"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("mv1UYABMCi3JHWKhsjA5uqjQkX6VpbbMRg6V"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(18888009),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(1213),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(149),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1UVKnfHCrzbUcfHS63xFeYbD4PfBCNAfYw"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("mv1UVKnfHCrzbUcfHS63xFeYbD4PfBCNAfYw"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(17427981),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(1119),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(138),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1UPcgbYJCHWj6xg15VD2z1mAPMHH1VY3Sn"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("mv1UPcgbYJCHWj6xg15VD2z1mAPMHH1VY3Sn"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(14207578),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(913),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(112),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1U7MzxbVWSVnjYWMwvrkWxReQwSzPkXcvB"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("mv1U7MzxbVWSVnjYWMwvrkWxReQwSzPkXcvB"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(12750656),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(818),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(101),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1TnGFAE2ehvQe5F2U5HbWZWb2FX423Vd8i"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("mv1TnGFAE2ehvQe5F2U5HbWZWb2FX423Vd8i"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(11966885),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(769),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(94),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1Tf75a2fUGmrThNuyse4vKFbPWM697SrNY"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("mv1Tf75a2fUGmrThNuyse4vKFbPWM697SrNY"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(11307149),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(726),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(89),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1Te9TpceACAx9ovhntt2VdsvkpLEDqvBvn"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("mv1Te9TpceACAx9ovhntt2VdsvkpLEDqvBvn"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(10889299),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(699),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(86),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1TWUZkUjutJHgo9t7FqxTNiqoFPuGEC4Bq"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("mv1TWUZkUjutJHgo9t7FqxTNiqoFPuGEC4Bq"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(7355283),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(472),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(58),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1TUaXztR5AK1BiRBxkFVLL49rkYLY3UqvZ"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("mv1TUaXztR5AK1BiRBxkFVLL49rkYLY3UqvZ"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(5221495),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(335),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(41),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1TSNZFAJaf8EQw4wreZjXtrcqZ8h4DFguU"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("mv1TSNZFAJaf8EQw4wreZjXtrcqZ8h4DFguU"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(2939210),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(189),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(23),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1TNgdUnE5udE6azQKy4HmDQJUWnKq2XQHu"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("mv1TNgdUnE5udE6azQKy4HmDQJUWnKq2XQHu"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(1984760),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(128),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(15),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1TGgFyRj2X6HovN3bCVSzMNZpJAuZGfmah"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("mv1TGgFyRj2X6HovN3bCVSzMNZpJAuZGfmah"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(1866216),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(120),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(14),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1SqGXUmNrBnnxE8zGueLteyK8nGf8MEX3A"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("mv1SqGXUmNrBnnxE8zGueLteyK8nGf8MEX3A"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(1641573),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(106),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(12),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1SpdbvjSeBH2sVGbwWdS6PjT3fTjcJXrND"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("mv1SpdbvjSeBH2sVGbwWdS6PjT3fTjcJXrND"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(1502458),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(97),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(11),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1SoxkkpjGAxigEX9jYEZjnhytAwYiJQXSM"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("mv1SoxkkpjGAxigEX9jYEZjnhytAwYiJQXSM"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(1459627),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(94),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(11),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1SXRSyhLnM9gSCc4YK3Ve6usdUN3pxNUtP"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("mv1SXRSyhLnM9gSCc4YK3Ve6usdUN3pxNUtP"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(1425001),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(91),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(11),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1SEq4K9xCso46WdqhDTPLHU6intuatA5Rz"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("mv1SEq4K9xCso46WdqhDTPLHU6intuatA5Rz"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(1406177),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(90),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(11),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1S8DRaNqHFRMNkpPgz3m5VnDGNSp4g4E71"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("mv1S8DRaNqHFRMNkpPgz3m5VnDGNSp4g4E71"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(1322354),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(85),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(10),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1RJjoUbdiZhG5ifQteRXVMPbooozCXwSbQ"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("mv1RJjoUbdiZhG5ifQteRXVMPbooozCXwSbQ"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(990125),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(64),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(7),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1REFFS2cy5hwqiDtxgeQmMpWTgoJdTwnBQ"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("mv1REFFS2cy5hwqiDtxgeQmMpWTgoJdTwnBQ"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(960009),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(62),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(7),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1QuSnBhYgaYwSq9Xy2985c5paAsFp9wBC5"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("mv1QuSnBhYgaYwSq9Xy2985c5paAsFp9wBC5"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(370571),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(24),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(2),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("KT1AmQTRDjTwfJDASJRJZdd7uJwDqs5W2mjA"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("KT1AmQTRDjTwfJDASJRJZdd7uJwDqs5W2mjA"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(289285),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(18),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(2),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1QtzoiuEztATbwANYP4gtEAdczn5ddV4Nj"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("mv1QtzoiuEztATbwANYP4gtEAdczn5ddV4Nj"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(275000),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(17),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(2),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1QmgAgBAMDHrx5th182efP3oygKWr1C2uU"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("mv1QmgAgBAMDHrx5th182efP3oygKWr1C2uU"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(200001),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(13),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(1),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1Qa4KUBhQKbwypURu3DCZVd1eyfAGwiVWp"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("mv1Qa4KUBhQKbwypURu3DCZVd1eyfAGwiVWp"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(172996),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(11),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(1),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("KT1Kmai449TQT76GZXbihwNFHTUy432y1Z6Y"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("KT1Kmai449TQT76GZXbihwNFHTUy432y1Z6Y"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(164629),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(10),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(1),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1QVVWyMc5yUJSja4ekcSceiw2kr8QnMZbF"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("mv1QVVWyMc5yUJSja4ekcSceiw2kr8QnMZbF"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(162848),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(10),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(1),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1QFwxFkC9c7fezjNE4VPATXfefbam1GFAt"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("mv1QFwxFkC9c7fezjNE4VPATXfefbam1GFAt"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(63473),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(4),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(0),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1Pf1ZpN3v4fBW3oSYhTj4wnf9XTEQATfDK"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("mv1Pf1ZpN3v4fBW3oSYhTj4wnf9XTEQATfDK"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(40787),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(2),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(0),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1PXgWu6bukpMfSCMgmLHqPvwCxUFkVuT3A"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("mv1PXgWu6bukpMfSCMgmLHqPvwCxUFkVuT3A"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(27475),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(1),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(0),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1PM6eS9LcrNZGQGiAuistbK64odUvw5CqG"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("mv1PM6eS9LcrNZGQGiAuistbK64odUvw5CqG"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(8937),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(0),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(0),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("KT19XE62UbrJ2gWW4ZWq2UxTQLhrnjBHLvBm"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("KT19XE62UbrJ2gWW4ZWq2UxTQLhrnjBHLvBm"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(826),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(0),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(0),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1PJLDRgEZGwxwCJsjM4hv3Rhx5AMbYuaJa"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("mv1PJLDRgEZGwxwCJsjM4hv3Rhx5AMbYuaJa"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(1),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(0),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(0),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("mv1PHN4Ck48rVjhj35FGWq23vYVSDKRD5sny"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("mv1PHN4Ck48rVjhj35FGWq23vYVSDKRD5sny"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(1),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(0),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(0),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs"),
				Delegator:        mavryk.MustParseAddress("KT1FtGbyLR1KV9oQGEYgBUpKPkEC8BcQn4cD"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("KT1FtGbyLR1KV9oQGEYgBUpKPkEC8BcQn4cD"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(0),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(0),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(0),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
		},
	}
	state.Init(".", state.StateInitOptions{})
	rawConfig := `{
        mavpay_config_version: 0
        baker: mv1T9xoFWkkNgy6wH5xeDg9XgdwnqznpuDXs
        payouts: {
                fee: 0.11
                transaction_fee_buffer: 0
                kt_transaction_fee_buffer: 0
        }
        delegators: {
                requirements: {
                        minimum_balance: 10
                }
        }
        network: {
                rpc_pool: [
					https://rpc.mavryk.network/
                ]
                mvkt_url: https://api.mavryk.network/
        }
        overdelegation: {
                protect: true
        }
        income_recipients: {
                donate: 0.01
        }
        notifications: [
        ]
	}`

	config, _ := configuration.LoadFromString([]byte(rawConfig))
	assert.NotNil(config)

	collector := mockPrepareCollector{}
	signer := mock.InitSimpleSigner()
	reporter := &mockPrepareReporter{}
	engineContext := common.NewPreparePayoutsEngineContext(&collector, signer, reporter, func(msg string) {})

	result, err := PreparePayouts([]*common.CyclePayoutBlueprint{&blueprint1, &blueprint2}, config, engineContext, &common.PreparePayoutsOptions{
		WaitForSufficientBalance: true,
		Accumulate:               true,
	})
	assert.NoError(err)
	assert.Len(result.Blueprints, 2)
	assertBlueprintsEqual(assert, result.Blueprints[0], &blueprint1)
	assertBlueprintsEqual(assert, result.Blueprints[1], &blueprint2)

	blueprint1InvalidCount := lo.Reduce(blueprint1.Payouts, func(acc int, recipe common.PayoutRecipe, _ int) int {
		if !recipe.IsValid {
			return acc + 1
		}
		return acc
	}, 0)
	blueprint2InvalidCount := lo.Reduce(blueprint2.Payouts, func(acc int, recipe common.PayoutRecipe, _ int) int {
		if !recipe.IsValid {
			return acc + 1
		}
		return acc
	}, 0)
	blueprint1ValidCount := len(blueprint1.Payouts) - blueprint1InvalidCount
	blueprint2ValidCount := len(blueprint2.Payouts) - blueprint2InvalidCount

	assert.Len(result.InvalidPayouts, blueprint1InvalidCount+blueprint2InvalidCount)
	assert.NotEqual(len(result.ValidPayouts), blueprint1ValidCount+blueprint2ValidCount) // because of accumulation
	assert.Len(result.ValidPayouts, 28)

}
