package core

import (
	"testing"

	"github.com/samber/lo"
	"github.com/stretchr/testify/assert"
	"github.com/mavryk-network/mavpay/common"
	"github.com/mavryk-network/mavpay/configuration"
	"github.com/mavryk-network/mavpay/state"
	"github.com/mavryk-network/mavpay/test/mock"
	"github.com/mavryk-network/gomavryk/codec"
	"github.com/mavryk-network/gomavryk/rpc"
	"github.com/mavryk-network/gomavryk/mavryk"
)

type mockPrepareCollector struct {
	mock.EmptyCollector
}

func (engine *mockPrepareCollector) GetId() string {
	return "mockPrepareCollector"
}

func (engine *mockPrepareCollector) IsRevealed(address mavryk.Address) (bool, error) {
	return true, nil
}

func (engine *mockPrepareCollector) GetBalance(addr mavryk.Address) (mavryk.Z, error) {
	return mavryk.NewZ(10000000000), nil
}

func (engine *mockPrepareCollector) Simulate(o *codec.Op, publicKey mavryk.Key) (*rpc.Receipt, error) {
	// rawRcpt := `{"Block":"BKiHLREqU3JkXfzEDYAkmmfX48gBDtYhMrpA98s7Aq4SzbUAB6M","Height":0,"List":0,"Pos":0,"Op":{"protocol":"PrihK96nBAFSxVL1GLJTVhu9YnzkMFiBeuJRPA8NwuZVZCE1L6i","chain_id":"NetXH12Aer3be93","hash":"oneDGhZacw99EEFaYDTtWfz5QEhUW3PPVFsHa7GShnLPuDn7gSd","branch":"BKiHLREqU3JkXfzEDYAkmmfX48gBDtYhMrpA98s7Aq4SzbUAB6M","contents":[{"kind":"transaction","metadata":{"balance_updates":null,"operation_result":{"status":"applied","balance_updates":[{"kind":"contract","origin":"block","category":"","change":"-1","contract":"tz1X7U9XxVz6NDxL4DSZhijME61PW45bYUJE","delegate":"","committer":"","participation":false,"revelation":false,"level":0,"cycle":0,"bond_id":{"smart_rollup":""},"staker":{"contract":"","delegate":"","baker":"","baker_own_stake":"","baker_edge":""},"delayed_operation_hash":"oneDGhZacw99EEFaYDTtWfz5QEhUW3PPVFsHa7GShnLPuDn7gSd"},{"kind":"contract","origin":"block","category":"","change":"1","contract":"tz1burnburnburnburnburnburnburjAYjjX","delegate":"","committer":"","participation":false,"revelation":false,"level":0,"cycle":0,"bond_id":{"smart_rollup":""},"staker":{"contract":"","delegate":"","baker":"","baker_own_stake":"","baker_edge":""},"delayed_operation_hash":"oneDGhZacw99EEFaYDTtWfz5QEhUW3PPVFsHa7GShnLPuDn7gSd"}],"consumed_gas":"0","consumed_milligas":"2170676","allocated_destination_contract":false,"originated_contracts":null,"storage_size":"0","paid_storage_size_diff":"0","global_address":"exprtWsu7N8st7XBhS685Qa2B4xP6TuTN9ve9UPCU29fV94ySDo5Va","ticket_updates":null,"ticket_receipt":null,"originated_rollup":"","level":0,"slot_header":{"version":"","level":0,"index":0,"commitment":""}},"delegate":"","level":0,"forbidden_delegate":""},"source":"tz1X7U9XxVz6NDxL4DSZhijME61PW45bYUJE","fee":"0","counter":"46810704","gas_limit":"520000","storage_limit":"30000","destination":"tz1burnburnburnburnburnburnburjAYjjX","amount":"1"},{"kind":"transaction","metadata":{"balance_updates":null,"operation_result":{"status":"applied","balance_updates":[{"kind":"contract","origin":"block","category":"","change":"-1","contract":"tz1X7U9XxVz6NDxL4DSZhijME61PW45bYUJE","delegate":"","committer":"","participation":false,"revelation":false,"level":0,"cycle":0,"bond_id":{"smart_rollup":""},"staker":{"contract":"","delegate":"","baker":"","baker_own_stake":"","baker_edge":""},"delayed_operation_hash":"oneDGhZacw99EEFaYDTtWfz5QEhUW3PPVFsHa7GShnLPuDn7gSd"},{"kind":"contract","origin":"block","category":"","change":"1","contract":"tz1burnburnburnburnburnburnburjAYjjX","delegate":"","committer":"","participation":false,"revelation":false,"level":0,"cycle":0,"bond_id":{"smart_rollup":""},"staker":{"contract":"","delegate":"","baker":"","baker_own_stake":"","baker_edge":""},"delayed_operation_hash":"oneDGhZacw99EEFaYDTtWfz5QEhUW3PPVFsHa7GShnLPuDn7gSd"}],"consumed_gas":"0","consumed_milligas":"2100040","allocated_destination_contract":false,"originated_contracts":null,"storage_size":"0","paid_storage_size_diff":"0","global_address":"exprtWsu7N8st7XBhS685Qa2B4xP6TuTN9ve9UPCU29fV94ySDo5Va","ticket_updates":null,"ticket_receipt":null,"originated_rollup":"","level":0,"slot_header":{"version":"","level":0,"index":0,"commitment":""}},"delegate":"","level":0,"forbidden_delegate":""},"source":"tz1X7U9XxVz6NDxL4DSZhijME61PW45bYUJE","fee":"0","counter":"46810705","gas_limit":"520000","storage_limit":"30000","destination":"tz1burnburnburnburnburnburnburjAYjjX","amount":"1"}],"signature":"sigMzJ4GVAvXEd2RjsKGfG2H9QvqTSKCZsuB2KiHbZRGFz72XgF6KaKADznh674fQgBatxw3xdHqTtMHUZAGRprxy64wg1aq"}}`

	var rcpt rpc.Receipt
	rcpt.Block = mavryk.MustParseBlockHash("BKiHLREqU3JkXfzEDYAkmmfX48gBDtYhMrpA98s7Aq4SzbUAB6M")
	rcpt.Height = 0
	rcpt.List = 0
	rcpt.Pos = 0
	rcpt.Op = &rpc.Operation{
		Protocol: mavryk.MustParseProtocolHash("PtSeouLouXkxhg39oWzjxDWaCydNfR3RxCUrNe4Q9Ro8BTehcbh"),
		ChainID:  mavryk.MustParseChainIdHash("NetXH12Aer3be93"),
		Hash:     mavryk.MustParseOpHash("oneDGhZacw99EEFaYDTtWfz5QEhUW3PPVFsHa7GShnLPuDn7gSd"),
		Branch:   mavryk.MustParseBlockHash("BKiHLREqU3JkXfzEDYAkmmfX48gBDtYhMrpA98s7Aq4SzbUAB6M"),
		Contents: lo.Map(o.Contents, func(c codec.Operation, _ int) rpc.TypedOperation {
			tx, isTransaction := c.(*codec.Transaction)
			if !isTransaction {
				panic("only transaction is supported in mock")
			}
			tx.GasLimit = 520000
			tx.StorageLimit = 30000
			tx.Fee = 1000
			return rpc.Transaction{
				Manager: rpc.Manager{
					GasLimit:     520000,
					StorageLimit: 30000,
					Fee:          1000,
				},
				Destination: tx.Destination,
				Amount:      tx.Amount.Int64(),
			}
		}),
	}

	return &rcpt, nil
}

type mockPrepareReporter struct {
	mock.EmptyReporter
}

func (engine *mockPrepareReporter) GetExistingReports(cycle int64) ([]common.PayoutReport, error) {
	switch cycle {
	case 1016:
		return []common.PayoutReport{
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1eYiA2SFVBKPK2UW24puEzbTiLHxMDjVtj"),
				Cycle:            1016,
				Recipient:        mavryk.MustParseAddress("tz1eYiA2SFVBKPK2UW24puEzbTiLHxMDjVtj"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(170719784),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(10963),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(1354),
				IsSuccess:        true,
			},
		}, nil
	case 1017:
		return []common.PayoutReport{
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1Sf9KWCfjN3nsPHB4cek2MXBuXq5qjBZrs"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("tz1Sf9KWCfjN3nsPHB4cek2MXBuXq5qjBZrs"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(12750656),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(818),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(101),
				IsSuccess:        true,
			},
		}, nil
	}
	return []common.PayoutReport{}, nil
}

// TODO:
func Test_Prepare(t *testing.T) {
	assert := assert.New(t)

	var blueprint1 common.CyclePayoutBlueprint = common.CyclePayoutBlueprint{
		Cycle:                    1016,
		OwnStakedBalance:         mavryk.NewZ(16421212933),
		OwnDelegatedBalance:      mavryk.NewZ(275708698),
		ExternalStakedBalance:    mavryk.NewZ(29383795329),
		ExternalDelegatedBalance: mavryk.NewZ(49100747788),
		EarnedBlockFees:          mavryk.NewZ(17100),
		EarnedRewards:            mavryk.NewZ(3545308),
		EarnedTotal:              mavryk.NewZ(3562408),
		BondIncome:               mavryk.NewZ(19693),
		FeeIncome:                mavryk.NewZ(385753),
		IncomeTotal:              mavryk.NewZ(405446),
		DonatedBonds:             mavryk.NewZ(198),
		DonatedFees:              mavryk.NewZ(3896),
		DonatedTotal:             mavryk.NewZ(4094),
		Payouts: []common.PayoutRecipe{
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1dKeXpumUQD5aCgk3jb7i7psWiRkzqJQdE"),
				Cycle:            1016,
				Recipient:        mavryk.MustParseAddress("tz1dKeXpumUQD5aCgk3jb7i7psWiRkzqJQdE"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(18996459719),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(1219794),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(150761),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1WZRZ6ciwRvkx5YVe5uVXKxrnzDQQevFCL"),
				Cycle:            1016,
				Recipient:        mavryk.MustParseAddress("tz1WZRZ6ciwRvkx5YVe5uVXKxrnzDQQevFCL"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(16995702660),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(1091322),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(134882),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1WpPaE47vtUT56MZGgKVi4VQCgEF95mvng"),
				Cycle:            1016,
				Recipient:        mavryk.MustParseAddress("tz1WpPaE47vtUT56MZGgKVi4VQCgEF95mvng"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(6704943203),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(430535),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(53212),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz2X42QzdRqoqeKCqZaGpoXD4VmzmwbuMJMb"),
				Cycle:            1016,
				Recipient:        mavryk.MustParseAddress("tz2X42QzdRqoqeKCqZaGpoXD4VmzmwbuMJMb"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(2067404437),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(132751),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(16407),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1PABDPXbg9rqz62umCaQ8YhCUajmoYK2Cb"),
				Cycle:            1016,
				Recipient:        mavryk.MustParseAddress("tz1PABDPXbg9rqz62umCaQ8YhCUajmoYK2Cb"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(767347858),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(49273),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(6089),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1dhJPohjESC3zzRnaJH7krf5wZPwLm4oH7"),
				Cycle:            1016,
				Recipient:        mavryk.MustParseAddress("tz1dhJPohjESC3zzRnaJH7krf5wZPwLm4oH7"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(664759189),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(42685),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(5275),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1gnuBF9TbBcgHPV2mUE96tBrW7PxqRmx1h"),
				Cycle:            1016,
				Recipient:        mavryk.MustParseAddress("tz1gnuBF9TbBcgHPV2mUE96tBrW7PxqRmx1h"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(598755901),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(38447),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(4751),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1UGkfyrT9yBt6U5PV7Qeui3pt3a8jffoWv"),
				Cycle:            1016,
				Recipient:        mavryk.MustParseAddress("tz1UGkfyrT9yBt6U5PV7Qeui3pt3a8jffoWv"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(507845869),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(32610),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(4030),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1XS2hdV3ygveRn1gxRJZgJ4yxFK1YnRrLn"),
				Cycle:            1016,
				Recipient:        mavryk.MustParseAddress("tz1XS2hdV3ygveRn1gxRJZgJ4yxFK1YnRrLn"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(405103709),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(26013),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(3214),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1P9A1noGEeoAQ6WNYM87BbJ3iaioorrws2"),
				Cycle:            1016,
				Recipient:        mavryk.MustParseAddress("tz1P9A1noGEeoAQ6WNYM87BbJ3iaioorrws2"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(313906924),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(20156),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(2491),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1eYiA2SFVBKPK2UW24puEzbTiLHxMDjVtj"),
				Cycle:            1016,
				Recipient:        mavryk.MustParseAddress("tz1eYiA2SFVBKPK2UW24puEzbTiLHxMDjVtj"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(170719784),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(10963),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(1354),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1X7U9XxVz6NDxL4DSZhijME61PW45bYUJE"),
				Cycle:            1016,
				Recipient:        mavryk.MustParseAddress("tz1X7U9XxVz6NDxL4DSZhijME61PW45bYUJE"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(165652388),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(10637),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(1314),
				Note:             "RECIPIENT_TARGETS_PAYOUT",
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1WWvSczbkko8p14qknj6d1KiK4T3ckQ33X"),
				Cycle:            1016,
				Recipient:        mavryk.MustParseAddress("tz1WWvSczbkko8p14qknj6d1KiK4T3ckQ33X"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(161298995),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(10357),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(1280),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1gKDahpLhd85yuJ6TEFAwrcnmcEG9gTkSi"),
				Cycle:            1016,
				Recipient:        mavryk.MustParseAddress("tz1gKDahpLhd85yuJ6TEFAwrcnmcEG9gTkSi"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(94164895),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(6046),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(747),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz2BZibvVaRzZq5kUWz1rcrJychdbHmoNZJE"),
				Cycle:            1016,
				Recipient:        mavryk.MustParseAddress("tz2BZibvVaRzZq5kUWz1rcrJychdbHmoNZJE"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(75318303),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(4837),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(597),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1cXDqHit4wsNv6dFHggKxDUBdpTkAaizyx"),
				Cycle:            1016,
				Recipient:        mavryk.MustParseAddress("tz1cXDqHit4wsNv6dFHggKxDUBdpTkAaizyx"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(74317010),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(4772),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(589),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz2NvuB26dtjUg11Gb49uocbYrJf26zN2QqW"),
				Cycle:            1016,
				Recipient:        mavryk.MustParseAddress("tz2NvuB26dtjUg11Gb49uocbYrJf26zN2QqW"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(70644509),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(4536),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(560),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1XyRgFTiNNZU7WzG3LDBi1bXWYPupBNBL2"),
				Cycle:            1016,
				Recipient:        mavryk.MustParseAddress("tz1XyRgFTiNNZU7WzG3LDBi1bXWYPupBNBL2"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(50000001),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(3211),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(396),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1dLZQyaopB2MDMdQC5nRt3Yx6RArVRubRh"),
				Cycle:            1016,
				Recipient:        mavryk.MustParseAddress("tz1dLZQyaopB2MDMdQC5nRt3Yx6RArVRubRh"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(34441415),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(2211),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(273),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1gMRKQWdhY5ZPUehpHofLswyL8Vexvfpbm"),
				Cycle:            1016,
				Recipient:        mavryk.MustParseAddress("tz1gMRKQWdhY5ZPUehpHofLswyL8Vexvfpbm"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(32415471),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(2081),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(257),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz2Lhty58UJvywseQH9vpGasHjuHtiitKZ56"),
				Cycle:            1016,
				Recipient:        mavryk.MustParseAddress("tz2Lhty58UJvywseQH9vpGasHjuHtiitKZ56"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(20256873),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(1301),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(160),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1hVZBTeTs9GZtpShYYuF92f7F2g4gWSQo9"),
				Cycle:            1016,
				Recipient:        mavryk.MustParseAddress("tz1hVZBTeTs9GZtpShYYuF92f7F2g4gWSQo9"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(18888009),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(1213),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(149),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1Nry5YPddf4VFDyunXLR8b8AtpvGJLMLZA"),
				Cycle:            1016,
				Recipient:        mavryk.MustParseAddress("tz1Nry5YPddf4VFDyunXLR8b8AtpvGJLMLZA"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(17427981),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(1119),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(138),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1boUGNrp8Z1WEAkqTHAPr5DennP7tQjF71"),
				Cycle:            1016,
				Recipient:        mavryk.MustParseAddress("tz1boUGNrp8Z1WEAkqTHAPr5DennP7tQjF71"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(14207578),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(913),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(112),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1Sf9KWCfjN3nsPHB4cek2MXBuXq5qjBZrs"),
				Cycle:            1016,
				Recipient:        mavryk.MustParseAddress("tz1Sf9KWCfjN3nsPHB4cek2MXBuXq5qjBZrs"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(12750656),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(818),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(101),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1frE7ArsC1spvQGizY5gBbJBtjnzGCgQ3y"),
				Cycle:            1016,
				Recipient:        mavryk.MustParseAddress("tz1frE7ArsC1spvQGizY5gBbJBtjnzGCgQ3y"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(11966885),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(769),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(94),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1hbseHXGm2XB7ivo1r3mbpH29c4GZE1aV2"),
				Cycle:            1016,
				Recipient:        mavryk.MustParseAddress("tz1hbseHXGm2XB7ivo1r3mbpH29c4GZE1aV2"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(11307149),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(726),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(89),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1f8LD3RZ9SMZUgsHQsQAX85EApD2cTXKES"),
				Cycle:            1016,
				Recipient:        mavryk.MustParseAddress("tz1f8LD3RZ9SMZUgsHQsQAX85EApD2cTXKES"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(10889299),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(699),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(86),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1dTmMLY7tan1HKfW5e3KxJcfZput6UuTH6"),
				Cycle:            1016,
				Recipient:        mavryk.MustParseAddress("tz1dTmMLY7tan1HKfW5e3KxJcfZput6UuTH6"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(7355283),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(472),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(58),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1SRqikWtR2KNpugCApreA9QeZuqh8swQMa"),
				Cycle:            1016,
				Recipient:        mavryk.MustParseAddress("tz1SRqikWtR2KNpugCApreA9QeZuqh8swQMa"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(5221495),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(335),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(41),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1iKqZc4CfrPwjcD7kx8MZtFtfL6YysKnPv"),
				Cycle:            1016,
				Recipient:        mavryk.MustParseAddress("tz1iKqZc4CfrPwjcD7kx8MZtFtfL6YysKnPv"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(2939210),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(189),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(23),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz2DWwmauKy4Dkak6X8ePY4Z91EsM36miYxB"),
				Cycle:            1016,
				Recipient:        mavryk.MustParseAddress("tz2DWwmauKy4Dkak6X8ePY4Z91EsM36miYxB"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(1984760),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(128),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(15),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1aCb6QKL7K4JxRTUTYjAER8qZH4zKAbigq"),
				Cycle:            1016,
				Recipient:        mavryk.MustParseAddress("tz1aCb6QKL7K4JxRTUTYjAER8qZH4zKAbigq"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(1866216),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(120),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(14),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1f4zxfTtjTKkrzzXNtQU73zGBcasW3xEBS"),
				Cycle:            1016,
				Recipient:        mavryk.MustParseAddress("tz1f4zxfTtjTKkrzzXNtQU73zGBcasW3xEBS"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(1641573),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(106),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(12),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1TG2bxjvmRMQakt8KVQ5S6CyLzMuSHx2qF"),
				Cycle:            1016,
				Recipient:        mavryk.MustParseAddress("tz1TG2bxjvmRMQakt8KVQ5S6CyLzMuSHx2qF"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(1502458),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(97),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(11),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1YibTr9kUchgG6wJjMwRar2NUfawxH48FT"),
				Cycle:            1016,
				Recipient:        mavryk.MustParseAddress("tz1YibTr9kUchgG6wJjMwRar2NUfawxH48FT"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(1459627),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(94),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(11),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1YtK9qUJffq2SqjhaJEGbufVHEBWDLPrSV"),
				Cycle:            1016,
				Recipient:        mavryk.MustParseAddress("tz1YtK9qUJffq2SqjhaJEGbufVHEBWDLPrSV"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(1425001),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(91),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(11),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz2DTjmLqMXSwhkpCFnV977vyhtYWbsP6nwo"),
				Cycle:            1016,
				Recipient:        mavryk.MustParseAddress("tz2DTjmLqMXSwhkpCFnV977vyhtYWbsP6nwo"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(1406177),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(90),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(11),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1eaCp9cc4FtTs3Wm6UgZZnEtZ9b1Peqewi"),
				Cycle:            1016,
				Recipient:        mavryk.MustParseAddress("tz1eaCp9cc4FtTs3Wm6UgZZnEtZ9b1Peqewi"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(1322354),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(85),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(10),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1MZ7ypArEoYocyyfscGaneNKM7bADhnQC4"),
				Cycle:            1016,
				Recipient:        mavryk.MustParseAddress("tz1MZ7ypArEoYocyyfscGaneNKM7bADhnQC4"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(990125),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(64),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(7),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1Qzov1LwEvSfHonRHr2EwQGto7ExrH43or"),
				Cycle:            1016,
				Recipient:        mavryk.MustParseAddress("tz1Qzov1LwEvSfHonRHr2EwQGto7ExrH43or"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(960009),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(62),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(7),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz28e4LURT9Kv6TXysL6szWYkKKqRmA1wDGq"),
				Cycle:            1016,
				Recipient:        mavryk.MustParseAddress("tz28e4LURT9Kv6TXysL6szWYkKKqRmA1wDGq"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(370571),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(24),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(2),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("KT1AmQTRDjTwfJDASJRJZdd7uJwDqs5W2mjA"),
				Cycle:            1016,
				Recipient:        mavryk.MustParseAddress("KT1AmQTRDjTwfJDASJRJZdd7uJwDqs5W2mjA"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(289285),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(18),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(2),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1UC8X57hKRmTbgJWsoos9njMy2SW3bKAAh"),
				Cycle:            1016,
				Recipient:        mavryk.MustParseAddress("tz1UC8X57hKRmTbgJWsoos9njMy2SW3bKAAh"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(275000),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(17),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(2),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1XX6ykvpfPGAkzeDaFPvvPqmRQoTwCvP4S"),
				Cycle:            1016,
				Recipient:        mavryk.MustParseAddress("tz1XX6ykvpfPGAkzeDaFPvvPqmRQoTwCvP4S"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(200001),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(13),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(1),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1P91PPAfukVdpgj153WqoLymrWDYCoyLRA"),
				Cycle:            1016,
				Recipient:        mavryk.MustParseAddress("tz1P91PPAfukVdpgj153WqoLymrWDYCoyLRA"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(172996),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(11),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(1),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("KT1Kmai449TQT76GZXbihwNFHTUy432y1Z6Y"),
				Cycle:            1016,
				Recipient:        mavryk.MustParseAddress("KT1Kmai449TQT76GZXbihwNFHTUy432y1Z6Y"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(164629),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(10),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(1),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz2JvpjaCGsynphe78Xbyu2kHUU2Ym8rxi8v"),
				Cycle:            1016,
				Recipient:        mavryk.MustParseAddress("tz2JvpjaCGsynphe78Xbyu2kHUU2Ym8rxi8v"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(162848),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(10),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(1),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1YDHyB7aBCvj5TCYiRQkjeVHfgtEYUDAd2"),
				Cycle:            1016,
				Recipient:        mavryk.MustParseAddress("tz1YDHyB7aBCvj5TCYiRQkjeVHfgtEYUDAd2"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(63473),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(4),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(0),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1VWKeeSqxdLsTfAyCSrwFVZnfgw4ZwaHWV"),
				Cycle:            1016,
				Recipient:        mavryk.MustParseAddress("tz1VWKeeSqxdLsTfAyCSrwFVZnfgw4ZwaHWV"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(40787),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(2),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(0),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1Xfkbwwa9ewNvYnesSXEYWGgS5gXVSQQVj"),
				Cycle:            1016,
				Recipient:        mavryk.MustParseAddress("tz1Xfkbwwa9ewNvYnesSXEYWGgS5gXVSQQVj"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(27475),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(1),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(0),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1Mv79qqYx2QX1NXYawrSrya13T7QoxCba9"),
				Cycle:            1016,
				Recipient:        mavryk.MustParseAddress("tz1Mv79qqYx2QX1NXYawrSrya13T7QoxCba9"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(8937),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(0),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(0),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("KT19XE62UbrJ2gWW4ZWq2UxTQLhrnjBHLvBm"),
				Cycle:            1016,
				Recipient:        mavryk.MustParseAddress("KT19XE62UbrJ2gWW4ZWq2UxTQLhrnjBHLvBm"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(826),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(0),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(0),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz2H4arakxXuzfo8NBVqTNgL5NBZ9b497Pfv"),
				Cycle:            1016,
				Recipient:        mavryk.MustParseAddress("tz2H4arakxXuzfo8NBVqTNgL5NBZ9b497Pfv"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(1),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(0),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(0),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1WxZvegEFTFSA8mqHWsBq97S15kS34JXqu"),
				Cycle:            1016,
				Recipient:        mavryk.MustParseAddress("tz1WxZvegEFTFSA8mqHWsBq97S15kS34JXqu"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(1),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(0),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(0),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("KT1FtGbyLR1KV9oQGEYgBUpKPkEC8BcQn4cD"),
				Cycle:            1016,
				Recipient:        mavryk.MustParseAddress("KT1FtGbyLR1KV9oQGEYgBUpKPkEC8BcQn4cD"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(0),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(0),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(0),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("KT1B5KPckWy2Mw99ii3wKuE4TQWKKQtSNXFE"),
				Cycle:            1016,
				Recipient:        mavryk.MustParseAddress("KT1B5KPckWy2Mw99ii3wKuE4TQWKKQtSNXFE"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(0),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(0),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(0),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.Address{}, // Represents an empty delegator address
				Cycle:            1016,
				Recipient:        mavryk.MustParseAddress("tz1UGkfyrT9yBt6U5PV7Qeui3pt3a8jffoWv"),
				Kind:             "donation",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(0),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(4094),
				Fee:              mavryk.NewZ(0),
				IsValid:          true,
			},
		},
	}

	var blueprint2 common.CyclePayoutBlueprint = common.CyclePayoutBlueprint{
		Cycle:                    1017,
		OwnStakedBalance:         mavryk.NewZ(16421212933),
		OwnDelegatedBalance:      mavryk.NewZ(275708698),
		ExternalStakedBalance:    mavryk.NewZ(29383795329),
		ExternalDelegatedBalance: mavryk.NewZ(49100747788),
		EarnedBlockFees:          mavryk.NewZ(17100),
		EarnedRewards:            mavryk.NewZ(3545308),
		EarnedTotal:              mavryk.NewZ(3562408),
		BondIncome:               mavryk.NewZ(19693),
		FeeIncome:                mavryk.NewZ(385753),
		IncomeTotal:              mavryk.NewZ(405446),
		DonatedBonds:             mavryk.NewZ(198),
		DonatedFees:              mavryk.NewZ(3896),
		DonatedTotal:             mavryk.NewZ(4094),
		Payouts: []common.PayoutRecipe{
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1dKeXpumUQD5aCgk3jb7i7psWiRkzqJQdE"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("tz1dKeXpumUQD5aCgk3jb7i7psWiRkzqJQdE"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(18996459719),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(1219794),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(150761),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1WZRZ6ciwRvkx5YVe5uVXKxrnzDQQevFCL"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("tz1WZRZ6ciwRvkx5YVe5uVXKxrnzDQQevFCL"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(16995702660),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(1091322),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(134882),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1WpPaE47vtUT56MZGgKVi4VQCgEF95mvng"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("tz1WpPaE47vtUT56MZGgKVi4VQCgEF95mvng"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(6704943203),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(430535),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(53212),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz2X42QzdRqoqeKCqZaGpoXD4VmzmwbuMJMb"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("tz2X42QzdRqoqeKCqZaGpoXD4VmzmwbuMJMb"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(2067404437),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(132751),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(16407),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1PABDPXbg9rqz62umCaQ8YhCUajmoYK2Cb"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("tz1PABDPXbg9rqz62umCaQ8YhCUajmoYK2Cb"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(767347858),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(49273),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(6089),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1dhJPohjESC3zzRnaJH7krf5wZPwLm4oH7"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("tz1dhJPohjESC3zzRnaJH7krf5wZPwLm4oH7"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(664759189),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(42685),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(5275),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1gnuBF9TbBcgHPV2mUE96tBrW7PxqRmx1h"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("tz1gnuBF9TbBcgHPV2mUE96tBrW7PxqRmx1h"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(598755901),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(38447),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(4751),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1UGkfyrT9yBt6U5PV7Qeui3pt3a8jffoWv"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("tz1UGkfyrT9yBt6U5PV7Qeui3pt3a8jffoWv"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(507845869),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(32610),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(4030),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1XS2hdV3ygveRn1gxRJZgJ4yxFK1YnRrLn"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("tz1XS2hdV3ygveRn1gxRJZgJ4yxFK1YnRrLn"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(405103709),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(26013),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(3214),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1P9A1noGEeoAQ6WNYM87BbJ3iaioorrws2"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("tz1P9A1noGEeoAQ6WNYM87BbJ3iaioorrws2"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(313906924),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(20156),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(2491),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1eYiA2SFVBKPK2UW24puEzbTiLHxMDjVtj"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("tz1eYiA2SFVBKPK2UW24puEzbTiLHxMDjVtj"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(170719784),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(10963),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(1354),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1X7U9XxVz6NDxL4DSZhijME61PW45bYUJE"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("tz1X7U9XxVz6NDxL4DSZhijME61PW45bYUJE"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(165652388),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(10637),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(1314),
				Note:             "RECIPIENT_TARGETS_PAYOUT",
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1WWvSczbkko8p14qknj6d1KiK4T3ckQ33X"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("tz1WWvSczbkko8p14qknj6d1KiK4T3ckQ33X"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(161298995),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(10357),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(1280),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1gKDahpLhd85yuJ6TEFAwrcnmcEG9gTkSi"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("tz1gKDahpLhd85yuJ6TEFAwrcnmcEG9gTkSi"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(94164895),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(6046),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(747),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz2BZibvVaRzZq5kUWz1rcrJychdbHmoNZJE"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("tz2BZibvVaRzZq5kUWz1rcrJychdbHmoNZJE"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(75318303),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(4837),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(597),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1cXDqHit4wsNv6dFHggKxDUBdpTkAaizyx"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("tz1cXDqHit4wsNv6dFHggKxDUBdpTkAaizyx"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(74317010),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(4772),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(589),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz2NvuB26dtjUg11Gb49uocbYrJf26zN2QqW"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("tz2NvuB26dtjUg11Gb49uocbYrJf26zN2QqW"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(70644509),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(4536),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(560),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1XyRgFTiNNZU7WzG3LDBi1bXWYPupBNBL2"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("tz1XyRgFTiNNZU7WzG3LDBi1bXWYPupBNBL2"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(50000001),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(3211),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(396),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1dLZQyaopB2MDMdQC5nRt3Yx6RArVRubRh"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("tz1dLZQyaopB2MDMdQC5nRt3Yx6RArVRubRh"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(34441415),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(2211),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(273),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1gMRKQWdhY5ZPUehpHofLswyL8Vexvfpbm"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("tz1gMRKQWdhY5ZPUehpHofLswyL8Vexvfpbm"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(32415471),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(2081),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(257),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz2Lhty58UJvywseQH9vpGasHjuHtiitKZ56"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("tz2Lhty58UJvywseQH9vpGasHjuHtiitKZ56"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(20256873),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(1301),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(160),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1hVZBTeTs9GZtpShYYuF92f7F2g4gWSQo9"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("tz1hVZBTeTs9GZtpShYYuF92f7F2g4gWSQo9"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(18888009),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(1213),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(149),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1Nry5YPddf4VFDyunXLR8b8AtpvGJLMLZA"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("tz1Nry5YPddf4VFDyunXLR8b8AtpvGJLMLZA"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(17427981),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(1119),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(138),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1boUGNrp8Z1WEAkqTHAPr5DennP7tQjF71"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("tz1boUGNrp8Z1WEAkqTHAPr5DennP7tQjF71"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(14207578),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(913),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(112),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1Sf9KWCfjN3nsPHB4cek2MXBuXq5qjBZrs"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("tz1Sf9KWCfjN3nsPHB4cek2MXBuXq5qjBZrs"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(12750656),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(818),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(101),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1frE7ArsC1spvQGizY5gBbJBtjnzGCgQ3y"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("tz1frE7ArsC1spvQGizY5gBbJBtjnzGCgQ3y"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(11966885),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(769),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(94),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1hbseHXGm2XB7ivo1r3mbpH29c4GZE1aV2"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("tz1hbseHXGm2XB7ivo1r3mbpH29c4GZE1aV2"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(11307149),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(726),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(89),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1f8LD3RZ9SMZUgsHQsQAX85EApD2cTXKES"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("tz1f8LD3RZ9SMZUgsHQsQAX85EApD2cTXKES"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(10889299),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(699),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(86),
				IsValid:          true,
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1dTmMLY7tan1HKfW5e3KxJcfZput6UuTH6"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("tz1dTmMLY7tan1HKfW5e3KxJcfZput6UuTH6"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(7355283),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(472),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(58),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1SRqikWtR2KNpugCApreA9QeZuqh8swQMa"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("tz1SRqikWtR2KNpugCApreA9QeZuqh8swQMa"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(5221495),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(335),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(41),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1iKqZc4CfrPwjcD7kx8MZtFtfL6YysKnPv"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("tz1iKqZc4CfrPwjcD7kx8MZtFtfL6YysKnPv"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(2939210),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(189),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(23),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz2DWwmauKy4Dkak6X8ePY4Z91EsM36miYxB"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("tz2DWwmauKy4Dkak6X8ePY4Z91EsM36miYxB"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(1984760),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(128),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(15),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1aCb6QKL7K4JxRTUTYjAER8qZH4zKAbigq"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("tz1aCb6QKL7K4JxRTUTYjAER8qZH4zKAbigq"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(1866216),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(120),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(14),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1f4zxfTtjTKkrzzXNtQU73zGBcasW3xEBS"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("tz1f4zxfTtjTKkrzzXNtQU73zGBcasW3xEBS"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(1641573),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(106),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(12),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1TG2bxjvmRMQakt8KVQ5S6CyLzMuSHx2qF"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("tz1TG2bxjvmRMQakt8KVQ5S6CyLzMuSHx2qF"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(1502458),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(97),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(11),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1YibTr9kUchgG6wJjMwRar2NUfawxH48FT"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("tz1YibTr9kUchgG6wJjMwRar2NUfawxH48FT"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(1459627),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(94),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(11),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1YtK9qUJffq2SqjhaJEGbufVHEBWDLPrSV"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("tz1YtK9qUJffq2SqjhaJEGbufVHEBWDLPrSV"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(1425001),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(91),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(11),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz2DTjmLqMXSwhkpCFnV977vyhtYWbsP6nwo"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("tz2DTjmLqMXSwhkpCFnV977vyhtYWbsP6nwo"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(1406177),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(90),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(11),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1eaCp9cc4FtTs3Wm6UgZZnEtZ9b1Peqewi"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("tz1eaCp9cc4FtTs3Wm6UgZZnEtZ9b1Peqewi"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(1322354),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(85),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(10),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1MZ7ypArEoYocyyfscGaneNKM7bADhnQC4"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("tz1MZ7ypArEoYocyyfscGaneNKM7bADhnQC4"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(990125),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(64),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(7),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1Qzov1LwEvSfHonRHr2EwQGto7ExrH43or"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("tz1Qzov1LwEvSfHonRHr2EwQGto7ExrH43or"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(960009),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(62),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(7),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz28e4LURT9Kv6TXysL6szWYkKKqRmA1wDGq"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("tz28e4LURT9Kv6TXysL6szWYkKKqRmA1wDGq"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(370571),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(24),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(2),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("KT1AmQTRDjTwfJDASJRJZdd7uJwDqs5W2mjA"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("KT1AmQTRDjTwfJDASJRJZdd7uJwDqs5W2mjA"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(289285),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(18),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(2),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1UC8X57hKRmTbgJWsoos9njMy2SW3bKAAh"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("tz1UC8X57hKRmTbgJWsoos9njMy2SW3bKAAh"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(275000),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(17),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(2),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1XX6ykvpfPGAkzeDaFPvvPqmRQoTwCvP4S"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("tz1XX6ykvpfPGAkzeDaFPvvPqmRQoTwCvP4S"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(200001),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(13),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(1),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1P91PPAfukVdpgj153WqoLymrWDYCoyLRA"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("tz1P91PPAfukVdpgj153WqoLymrWDYCoyLRA"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(172996),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(11),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(1),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("KT1Kmai449TQT76GZXbihwNFHTUy432y1Z6Y"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("KT1Kmai449TQT76GZXbihwNFHTUy432y1Z6Y"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(164629),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(10),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(1),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz2JvpjaCGsynphe78Xbyu2kHUU2Ym8rxi8v"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("tz2JvpjaCGsynphe78Xbyu2kHUU2Ym8rxi8v"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(162848),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(10),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(1),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1YDHyB7aBCvj5TCYiRQkjeVHfgtEYUDAd2"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("tz1YDHyB7aBCvj5TCYiRQkjeVHfgtEYUDAd2"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(63473),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(4),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(0),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1VWKeeSqxdLsTfAyCSrwFVZnfgw4ZwaHWV"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("tz1VWKeeSqxdLsTfAyCSrwFVZnfgw4ZwaHWV"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(40787),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(2),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(0),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1Xfkbwwa9ewNvYnesSXEYWGgS5gXVSQQVj"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("tz1Xfkbwwa9ewNvYnesSXEYWGgS5gXVSQQVj"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(27475),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(1),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(0),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1Mv79qqYx2QX1NXYawrSrya13T7QoxCba9"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("tz1Mv79qqYx2QX1NXYawrSrya13T7QoxCba9"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(8937),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(0),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(0),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("KT19XE62UbrJ2gWW4ZWq2UxTQLhrnjBHLvBm"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("KT19XE62UbrJ2gWW4ZWq2UxTQLhrnjBHLvBm"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(826),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(0),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(0),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz2H4arakxXuzfo8NBVqTNgL5NBZ9b497Pfv"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("tz2H4arakxXuzfo8NBVqTNgL5NBZ9b497Pfv"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(1),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(0),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(0),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("tz1WxZvegEFTFSA8mqHWsBq97S15kS34JXqu"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("tz1WxZvegEFTFSA8mqHWsBq97S15kS34JXqu"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(1),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(0),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(0),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            mavryk.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        mavryk.MustParseAddress("KT1FtGbyLR1KV9oQGEYgBUpKPkEC8BcQn4cD"),
				Cycle:            1017,
				Recipient:        mavryk.MustParseAddress("KT1FtGbyLR1KV9oQGEYgBUpKPkEC8BcQn4cD"),
				Kind:             "delegator reward",
				TxKind:           "mav",
				FATokenId:        mavryk.NewZ(0),
				DelegatedBalance: mavryk.NewZ(0),
				StakedBalance:    mavryk.NewZ(0),
				Amount:           mavryk.NewZ(0),
				FeeRate:          0.11,
				Fee:              mavryk.NewZ(0),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
		},
	}
	state.Init(".", state.StateInitOptions{})
	rawConfig := `{
        mavpay_config_version: 0
        baker: tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM
        payouts: {
                fee: 0.11
                transaction_fee_buffer: 0
                kt_transaction_fee_buffer: 0
        }
        delegators: {
                requirements: {
                        minimum_balance: 10
                }
        }
        network: {
                rpc_pool: [
					https://rpc.mavryk.network/
                ]
                mvkt_url: https://api.mavryk.network/
        }
        overdelegation: {
                protect: true
        }
        income_recipients: {
                donate: 0.01
        }
        notifications: [
        ]
	}`

	config, _ := configuration.LoadFromString([]byte(rawConfig))
	assert.NotNil(config)

	collector := mockPrepareCollector{}
	signer := mock.InitSimpleSigner()
	reporter := &mockPrepareReporter{}
	engineContext := common.NewPreparePayoutsEngineContext(&collector, signer, reporter, func(msg string) {})

	result, err := PreparePayouts([]*common.CyclePayoutBlueprint{&blueprint1, &blueprint2}, config, engineContext, &common.PreparePayoutsOptions{
		WaitForSufficientBalance: true,
		Accumulate:               true,
	})
	assert.NoError(err)
	assert.Len(result.Blueprints, 2)
	assertBlueprintsEqual(assert, result.Blueprints[0], &blueprint1)
	assertBlueprintsEqual(assert, result.Blueprints[1], &blueprint2)

	blueprint1InvalidCount := lo.Reduce(blueprint1.Payouts, func(acc int, recipe common.PayoutRecipe, _ int) int {
		if !recipe.IsValid {
			return acc + 1
		}
		return acc
	}, 0)
	blueprint2InvalidCount := lo.Reduce(blueprint2.Payouts, func(acc int, recipe common.PayoutRecipe, _ int) int {
		if !recipe.IsValid {
			return acc + 1
		}
		return acc
	}, 0)
	blueprint1ValidCount := len(blueprint1.Payouts) - blueprint1InvalidCount
	blueprint2ValidCount := len(blueprint2.Payouts) - blueprint2InvalidCount

	assert.Len(result.InvalidPayouts, blueprint1InvalidCount+blueprint2InvalidCount)
	assert.NotEqual(len(result.ValidPayouts), blueprint1ValidCount+blueprint2ValidCount) // because of accumulation
	assert.Len(result.ValidPayouts, 28)

}
